# ─────────────────────────────────────────────────────────────────────────────
# SpendSense AI — Multi-stage Dockerfile
# ─────────────────────────────────────────────────────────────────────────────
# Stage 1 → deps:     install production + dev dependencies
# Stage 2 → builder:  run `next build` (generates .next/standalone)
# Stage 3 → runner:   copy only the standalone output; minimal final image
#
# Result: ~150 MB image vs ~1 GB if node_modules were included naively.
# ─────────────────────────────────────────────────────────────────────────────

# ── Stage 1: Install dependencies ────────────────────────────────────────────
FROM node:20-alpine AS deps

# Required by better-sqlite3 (native module — needs build tools)
RUN apk add --no-cache libc6-compat python3 make g++

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

# ── Stage 2: Build ────────────────────────────────────────────────────────────
FROM node:20-alpine AS builder

RUN apk add --no-cache libc6-compat python3 make g++

WORKDIR /app

# Copy deps from previous stage
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Produce standalone output (.next/standalone + .next/static)
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=production

RUN npm run build

# ── Stage 3: Production runner ────────────────────────────────────────────────
FROM node:20-alpine AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
# Port the Next.js standalone server listens on
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# Create a non-root user for security
RUN addgroup --system --gid 1001 nodejs \
 && adduser  --system --uid 1001 nextjs

# Copy the standalone server bundle (minimal — no full node_modules)
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static    ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public          ./public

# Copy the migration script so we can run it at container startup
COPY --from=builder --chown=nextjs:nodejs /app/src/data/migrate.ts   ./src/data/migrate.ts
COPY --from=builder --chown=nextjs:nodejs /app/src/data/schema.sql   ./src/data/schema.sql
COPY --from=builder --chown=nextjs:nodejs /app/src/data/db.ts        ./src/data/db.ts
COPY --from=builder --chown=nextjs:nodejs /app/tsconfig.json         ./tsconfig.json

# SQLite DB lives on a mounted volume (see docker-compose.yml)
# The SQLITE_PATH env var tells db.ts where to find/create the file.
ENV SQLITE_PATH=/data/spendsense.db

# Create the data directory and set ownership
RUN mkdir -p /data && chown nextjs:nodejs /data

USER nextjs

EXPOSE 3000

# server.js is the standalone Next.js entry point generated by `next build`
CMD ["node", "server.js"]
