/**
 * src/data/types.ts
 *
 * Canonical TypeScript domain types for the SpendSense data layer.
 * These types are shared across `src/data/` only. API and UI layers
 * must not import from this file directly — they use the Zod-inferred
 * types declared in their own schema files.
 *
 * Invariants enforced:
 *  - SystemCategory is a strict discriminated union (no open strings).
 *  - ExpenseRecord requires user_id on every row (multi-tenant isolation).
 *  - All monetary amounts are stored as numbers (cents or decimals depending on currency).
 */

// ---------------------------------------------------------------------------
// Category Enum — enforces the Category Enum Invariant (architecture.md §3.2)
// ---------------------------------------------------------------------------

export type SystemCategory = string;

export const SYSTEM_CATEGORIES: readonly SystemCategory[] = [
  'Food',
  'Rent',
  'Entertainment',
  'Others',
] as const;

/** Type-guard to validate that an unknown string is a valid category (now just any non-empty string). */
export function isSystemCategory(value: unknown): value is SystemCategory {
  return typeof value === 'string' && value.length > 0;
}

// ---------------------------------------------------------------------------
// User Record
// ---------------------------------------------------------------------------

export interface UserRecord {
  /** UUID primary key — generated by the database. */
  id: string;
  email: string;
  /** bcrypt-hashed password — NULL for OAuth-only accounts. */
  password_hash: string | null;
  /** ISO 4217 three-letter currency code chosen during onboarding (e.g. "USD"). */
  currency: string;
  /** ISO 3166-1 alpha-2 country code chosen during onboarding (e.g. "US"). */
  country: string;
  created_at: Date;
  updated_at: Date;
}

// ---------------------------------------------------------------------------
// OAuth Provider Record
// ---------------------------------------------------------------------------

export type OAuthProvider = 'google' | 'apple';

export interface OAuthAccountRecord {
  id: string;
  user_id: string;
  provider: OAuthProvider;
  /** Subject identifier returned by the OAuth provider. */
  provider_user_id: string;
  created_at: Date;
}

// ---------------------------------------------------------------------------
// Session Record
// ---------------------------------------------------------------------------

export interface SessionRecord {
  id: string;
  user_id: string;
  /** Opaque token stored in the client's HttpOnly cookie. */
  token_hash: string;
  expires_at: Date;
  created_at: Date;
}

// ---------------------------------------------------------------------------
// Expense Record — core ledger row
// ---------------------------------------------------------------------------

export interface ExpenseRecord {
  /** UUID primary key. */
  id: string;
  /** FK → users.id — required on every query (Parameterized Data Isolation Invariant). */
  user_id: string;
  /** Decimal amount as stored. Must be positive. */
  amount: number;
  /** ISO 4217 three-letter code — copied from the user's profile at insert time. */
  currency: string;
  /** Strict enum enforced at both DB and application layers. */
  category: SystemCategory;
  /** ISO 8601 date-only string (YYYY-MM-DD). */
  date: string;
  /** Plain-text merchant or memo note. Max 255 characters. */
  description: string;
  created_at: Date;
  updated_at: Date;
}

// ---------------------------------------------------------------------------
// Input shapes (used by the data-access layer before Zod validation)
// ---------------------------------------------------------------------------

/** Payload required to create a new expense row. Excludes auto-generated fields. */
export interface CreateExpenseInput {
  user_id: string;
  amount: number;
  currency: string;
  category: SystemCategory;
  date: string;
  description: string;
}

/** Payload required to create a new user row. */
export interface CreateUserInput {
  email: string;
  password_hash: string | null;
  currency: string;
  country: string;
}
